backend:
  name: git-gateway
  repo: github.com/relentlessslog.github.io
  branch: main
  api_root: https://api.github.com
  site_domain: relentlessslog.github.io
  base_url: https://api.netlify.com
  auth_endpoints: auth
  cms_label_prefix: netlify-cms/
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "blog" #Used in routes for admin
    label: "Blog" #Used in the UI
    folder: "src/blog" #Path to input folder 
    create: true #Allow users to create new content
    slug: "{{ slug }}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}